export const ADD_TIMEZONE = 'ADD_TIMEZONE';
export const DELETE_TIMEZONE = 'DELETE_TIMEZONE';
export const TOGGLE_24_HOUR_DISPLAY = 'TOGGLE_24_HOUR_DISPLAY';
export const UPDATE_TIME_BY_MINUTES = 'UPDATE_TIME_BY_MINUTES';
export const RESET_CURSOR_TO_CURRENT = 'RESET_CURSOR_TO_CURRENT';
